CC = g++
IDIRS = -I/home/gopiandcode/Documents/C++/CPlusPlusProjects/stdlib/CH4
CFLAGS = -Wall -Werror $(IDIRS)
PROG = main.exe
OBJS = main.o

all: $(PROG)

$(PROG): $(OBJS)
	$(CC) $(LDLIBS) $(CFLAGS) $(OBJS) -o $@


main.o: main.cpp


